# ~/.bash_profile: executed by bash(1) for login shells.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/login.defs
#umask 022

if [ -z "$DISPLAY" ] && [ $(tty) == /dev/tty1 ]; then
    xinit
fi
