#!/bin/sh
### BEGIN INIT INFO
# Provides:          musicbox
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Musicbox player
### END INIT INFO

SCRIPT=/usr/local/bin/musicbox

PIDFILE=/var/run/musicbox.pid
LOGFILE=/var/log/musicbox.log

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Musicbox already running'
    return 1
  fi
  echo 'Starting Musicbox...'
  $SCRIPT > $LOGFILE 2>&1 & echo $! > $PIDFILE
  echo 'Started'
}

stop() {
  if [ ! -f $PIDFILE ] || ! kill -0 $(cat $PIDFILE); then
    echo 'Musicbox not running'
    return 1
  fi
  echo 'Stopping Musicbox...'
  kill -15 $(cat $PIDFILE) && rm -f $PIDFILE
  echo 'Stopped'
}

status() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Musicbox running'
  else
    echo 'Musicbox not running'
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
esac

