#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
        for f in /etc/X11/xinit/xinitrc.d/*; do
                [ -x "$f" ] && . "$f"
        done
        unset f
fi

xrdb -merge ~/.Xresources         		# update x resources db

xrandr --size 1280x1024				# sets the X resolution
xsetroot -cursor_name left_ptr  		# sets the cursor icon
xsetroot -solid "#000000"			# sets the background image

cd /usr/local/src/musicbox			# sets the src directory
exec sudo ./server.py				# starts the window manager
